name: Build and Publish HTML5
on:
  push:
    branches: [ "main" ]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Export HTML5 with Godot
        uses: firebelley/godot-export-action@v2
        with:
          project_path: .
          godot_version: '4.1.2'
          export_preset: 'HTML5'
          export_path: 'build/html5'

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: build/html5
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
